gh issue create --title "Feature: Thêm Modal xác nhận khi xóa thi thể để tránh xóa nhầm" --body "Thêm state quản lý và hiển thị một component Modal hỏi 'Bạn có chắc chắn muốn xóa?' trong CorpseList.razor. Gọi hàm xóa và hiển thị Toast khi đồng ý." --assignee "newiexk-cyber"
gh issue create --title "UI/UX: Cải thiện trang Dashboard (Thêm hiệu ứng Count-up và Cảnh báo khẩn cấp)" --body "Trong KpiCard.razor, thêm animation đếm số từ 0 lên giá trị thực. Đồng thời thêm khối 'Cảnh báo khẩn cấp' cho các thi thể quá hạn." --assignee "newiexk-cyber"
gh issue create --title "Feature: Thêm chức năng In báo cáo giả lập (Export to Print)" --body "Thêm nút 'In báo cáo' gọi JS interop window.print() trong ReportPage.razor và viết css @media print để ẩn các layout không cần thiết." --assignee "newiexk-cyber"

gh issue create --title "Feature: Xây dựng Service và hoàn thiện Form Liên hệ (Contact)" --body "Tạo IContactService và kết nối với form Contact.razor sử dụng EditForm, bổ sung Validation DataAnnotations." --assignee "Simpson-31ev3n"
gh issue create --title "UI/UX: Cập nhật Navbar hiển thị dựa trên trạng thái Đăng nhập (Auth State)" --body "Dùng thẻ AuthorizeView trong PublicNavBar.razor để hiển thị nút 'Dashboard' và 'Đăng xuất' nếu đã login, ngược lại hiển thị nút 'Đăng nhập'." --assignee "Simpson-31ev3n"

gh issue create --title "Architecture: Bổ sung các Models mới và chuẩn hóa Enums trạng thái" --body "Tạo các model AppUser, ActivityLog, Report. Tạo các Enum như CorpseStatus, ShiftType, UserRole và áp dụng vào các Model hiện tại thay vì dùng string." --assignee "khanhphamvn222"
gh issue create --title "Feature: Kết nối giao diện CorpseList và ShiftCalendar với tầng Service" --body "Xóa dữ liệu cứng, Inject ICorpseService và IShiftService vào các page và gọi hàm lấy dữ liệu trong OnInitializedAsync." --assignee "khanhphamvn222"
gh issue create --title "UI/UX: Tạo component LoadingSpinner chung cho toàn dự án" --body "Tạo component LoadingSpinner bằng SVG/Tailwind để tái sử dụng hiển thị trong lúc chờ fetch dữ liệu từ service." --assignee "khanhphamvn222"

gh issue create --title "UI/UX: Hoàn thiện Layout động (Responsive Sidebar & Mobile Header)" --body "Thiết kế Sidebar dạng Hamburger menu trượt (collapsible) và xử lý animation mượt mà bằng GSAP trên điện thoại di động." --assignee "BDTG"
gh issue create --title "Architecture: Cấu hình và thiết lập ứng dụng PWA (Progressive Web App) cho MorgueManager.Web" --body "Đăng ký Service Worker và tạo manifest.json trong wwwroot để hỗ trợ cài đặt ứng dụng trên máy tính/điện thoại và lưu trữ offline cơ bản các layout." --assignee "BDTG"
gh issue create --title "Feature: Tối ưu hóa UI/UX và cải tiến hiển thị Dark/Light Mode đồng bộ cho các trang" --body "Cải thiện đồng bộ giao diện Dark Mode / Light Mode trên các component dùng chung như Sidebar, Header và các card thông tin, đảm bảo độ tương phản màu sắc chuẩn WCAG." --assignee "BDTG"
