// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorgueManager.API.Data;

#nullable disable

namespace MorgueManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624075650_UpdateTimestampBehavior")]
    partial class UpdateTimestampBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MorgueManager.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MorgueManager.API.Models.BillingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorpseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<double>("ServiceFee")
                        .HasColumnType("float");

                    b.Property<double>("StorageFeePerDay")
                        .HasColumnType("float");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BillingRecords");
                });

            modelBuilder.Entity("MorgueManager.API.Models.Corpse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Biohazard")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateAdmitted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysStored")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageSlotId")
                        .HasColumnType("int");

                    b.Property<string>("StorageUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Temp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Corpses");
                });

            modelBuilder.Entity("MorgueManager.API.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MorgueManager.API.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2026, 6, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2026, 6, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2026, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 51,
                            Date = new DateTime(2026, 6, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 52,
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 53,
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 54,
                            Date = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 55,
                            Date = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 56,
                            Date = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 57,
                            Date = new DateTime(2026, 6, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 58,
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 59,
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 60,
                            Date = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 61,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 62,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 63,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 64,
                            Date = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 65,
                            Date = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 66,
                            Date = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 67,
                            Date = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 68,
                            Date = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 69,
                            Date = new DateTime(2026, 6, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 70,
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 71,
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 72,
                            Date = new DateTime(2026, 6, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 73,
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 74,
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 75,
                            Date = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 76,
                            Date = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 77,
                            Date = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 78,
                            Date = new DateTime(2026, 6, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 79,
                            Date = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 80,
                            Date = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 81,
                            Date = new DateTime(2026, 6, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 82,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 83,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 84,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 85,
                            Date = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 86,
                            Date = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 87,
                            Date = new DateTime(2026, 6, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 88,
                            Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca sáng",
                            ShiftType = "Morning",
                            StaffEmail = "staff@hospital.vn"
                        },
                        new
                        {
                            Id = 89,
                            Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca chiều",
                            ShiftType = "Afternoon",
                            StaffEmail = "manager@hospital.vn"
                        },
                        new
                        {
                            Id = 90,
                            Date = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Ca đêm",
                            ShiftType = "Night",
                            StaffEmail = "staff@hospital.vn"
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.StorageSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StorageSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-01",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 2,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-02",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 3,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-03",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 4,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-04",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 5,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-05",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 6,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-06",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 7,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-07",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 8,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-08",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 9,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-09",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 10,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-10",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 11,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-01",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 12,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-02",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 13,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-03",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 14,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-04",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 15,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-05",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 16,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-06",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 17,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-07",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 18,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-08",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 19,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-09",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 20,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-10",
                            Status = 0,
                            UnitName = "Cold Room B"
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.TemperatureLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StorageSlotId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TemperatureLogs");
                });

            modelBuilder.Entity("MorgueManager.API.Models.TransportTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorpseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportTrips");
                });

            modelBuilder.Entity("MorgueManager.API.Models.TransportVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TransportVehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "51B-12345",
                            Model = "Ford Transit Special Ambulance",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "51B-67890",
                            Model = "Mercedes-Benz Sprinter Hearse",
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "51B-55555",
                            Model = "Hyundai Staria Mortuary Vehicle",
                            Status = 0
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User",
                            Email = "admin@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manager User",
                            Email = "manager@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Staff User",
                            Email = "staff@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.Corpse", b =>
                {
                    b.OwnsOne("MorgueManager.API.Models.AutopsyReport", "AutopsyReport", b1 =>
                        {
                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("ConcludingCause")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("InternalExamDetails")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PathologistName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Timestamp")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ToxicologyResult")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CorpseId");

                            b1.ToTable("Corpses");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsMany("MorgueManager.API.Models.Belonging", "Belongings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Desc")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("HasImage")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("Belonging");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsMany("MorgueManager.API.Models.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("Document");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsOne("MorgueManager.API.Models.EmbalmingInfo", "EmbalmingInfo", b1 =>
                        {
                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("ChemicalsUsed")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DateEmbalmed")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("EmbalmerName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsEmbalmed")
                                .HasColumnType("bit");

                            b1.HasKey("CorpseId");

                            b1.ToTable("Corpses");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsMany("MorgueManager.API.Models.HistoryEntry", "History", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Timestamp")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("HistoryEntry");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsOne("MorgueManager.API.Models.NextOfKinInfo", "NextOfKin", b1 =>
                        {
                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CorpseId");

                            b1.ToTable("Corpses");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.Navigation("AutopsyReport");

                    b.Navigation("Belongings");

                    b.Navigation("Documents");

                    b.Navigation("EmbalmingInfo")
                        .IsRequired();

                    b.Navigation("History");

                    b.Navigation("NextOfKin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
