// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MorgueManager.API.Data;

#nullable disable

namespace MorgueManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615155534_ComprehensiveUpgrade")]
    partial class ComprehensiveUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MorgueManager.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MorgueManager.API.Models.Corpse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateAdmitted")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysStored")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageSlot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StorageSlotId")
                        .HasColumnType("int");

                    b.Property<string>("StorageUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Temp")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Corpses");
                });

            modelBuilder.Entity("MorgueManager.API.Models.StorageSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CurrentTemperature")
                        .HasColumnType("float");

                    b.Property<string>("SlotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StorageSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-01",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 2,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-02",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 3,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-03",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 4,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-04",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 5,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-05",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 6,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-06",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 7,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-07",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 8,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-08",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 9,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-09",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 10,
                            CurrentTemperature = 4.0,
                            SlotNumber = "A-10",
                            Status = 0,
                            UnitName = "Cold Room A"
                        },
                        new
                        {
                            Id = 11,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-01",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 12,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-02",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 13,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-03",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 14,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-04",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 15,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-05",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 16,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-06",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 17,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-07",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 18,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-08",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 19,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-09",
                            Status = 0,
                            UnitName = "Cold Room B"
                        },
                        new
                        {
                            Id = 20,
                            CurrentTemperature = 4.0,
                            SlotNumber = "B-10",
                            Status = 0,
                            UnitName = "Cold Room B"
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.TemperatureLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StorageSlotId")
                        .HasColumnType("int");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TemperatureLogs");
                });

            modelBuilder.Entity("MorgueManager.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Admin User",
                            Email = "admin@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Manager User",
                            Email = "manager@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayName = "Staff User",
                            Email = "staff@hospital.vn",
                            PasswordHash = "$2a$11$V6VVNz2xMBegNqXAB8HJNuBpYZFm9DClOl.fpQsvdB/up2G6TGK.W",
                            Role = "Staff"
                        });
                });

            modelBuilder.Entity("MorgueManager.API.Models.Corpse", b =>
                {
                    b.OwnsMany("MorgueManager.API.Models.Belonging", "Belongings", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Condition")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Desc")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("HasImage")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("Belonging");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsMany("MorgueManager.API.Models.Document", "Documents", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Size")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("Document");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsMany("MorgueManager.API.Models.HistoryEntry", "History", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("By")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Detail")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Timestamp")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("Id");

                            b1.HasIndex("CorpseId");

                            b1.ToTable("HistoryEntry");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.OwnsOne("MorgueManager.API.Models.NextOfKinInfo", "NextOfKin", b1 =>
                        {
                            b1.Property<int>("CorpseId")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CorpseId");

                            b1.ToTable("Corpses");

                            b1.WithOwner()
                                .HasForeignKey("CorpseId");
                        });

                    b.Navigation("Belongings");

                    b.Navigation("Documents");

                    b.Navigation("History");

                    b.Navigation("NextOfKin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
